### ISSUE TITLE
Create a multi-<object> part

### ISSUE THREAD

**Issue by mvelayati** [3MFConsortium/3mf-samples#2]
I want to create a multi .3mf shape, I used the "Cube" code and created some kind of a loop to create multiple mesh objects but my code is not outputting anything. Since there should be one for different parts, do I have to create multiple tags? I don't see the command for it.

**Comment by alexanderoster** [comment]
Hi there,

can you post an example of your code somewhere (like pastebin.com)? I would love to help you troubleshoot the issue.

All the best,
 Alex

**Comment by mvelayati** [comment]
Thank you Alex for the reply,
I solved the issue but I have questions that I couldn't find online because the the format is new I guess.
I would like to know if currently there are companies who can manufacture .3mf parts?
I would to get in touch with you(maybe via email) to talk more about this.

**Comment by alexanderoster** [comment]
Hi there,
sure! I think you can manufacture parts at both shapeways.com and i.materialise.com
If you have further questions, just reach out to me via email.

All the best,
 Alex
