### ISSUE TITLE
Undefined XML namespace in multiprop-metallic.3mf

### ISSUE THREAD

**Issue by Mugen87** [3MFConsortium/3mf-samples#24]
I'm using the sample files to add new features to the `3MF` importer of `three.js`. When working with [multiprop-metallic.3mf](https://github.com/3MFConsortium/3mf-samples/blob/master/examples/material/multiprop-metallic.3mf), I've realized that selecting the child elements of `pbmetallicdisplayproperties` via `querySelectorAll()` does not work because `pbmetallic` is assigned to an undefined XML namespace (`ms`). Here is the problematic part:

```xml
<m:pbmetallicdisplayproperties id="9">
    <ms:pbmetallic name="MetalProp" metallicness="1" roughness="0.2" />
</m:pbmetallicdisplayproperties>
```
It would be great if the file can be fixed so I can used it to verify the loader's logic 😇

**Comment by jordig100** [comment]
@Mugen87, files updated in the fixes branch. You might use it, before they got published.
