### ISSUE TITLE
Multiproperty examples are not valid

### ISSUE THREAD

**Issue by martinweismann** [3MFConsortium/3mf-samples#25]
Some of the multiproperties examples are invalid:
a.	https://github.com/3MFConsortium/3mf-samples/blob/master/examples/material/multiprop-opaque.3mf has no object-level pid
b.	https://github.com/3MFConsortium/3mf-samples/blob/master/examples/material/multiprop-translucent.3mf has no object-level pid and prefixes "translucent" with at “ms” namespace-prefix
c.	https://github.com/3MFConsortium/3mf-samples/blob/master/examples/material/multiprop-metallic.3mf has no object-level pid and prefixes "pbmetallic" with at “ms” namespace-prefix

**Comment by jordig100** [comment]
Created pull request with this fix and pending changes.

**Comment by martinweismann** [comment]
@jordig100 : did you remove the multiprop-translucent and -metallic on purpose in the PR?

**Comment by jordig100** [comment]
Restored the files removed by mistake
