### ISSUE TITLE
Please clarify the license of the sample files

### ISSUE THREAD

**Issue by t-paul** [3MFConsortium/3mf-samples#5]
I can't find any declaration of license for the sample files.

It would be useful to know what the intention is, e.g. if it's possible to distribute the sample files along with the development package in Linux distributions.

**Comment by pencerw** [comment]
@t-paul, very sorry for the delay. The sample files are BSD-2, which is now included in the repo.

**Comment by t-paul** [comment]
Awesome, thanks.
